_BASE_: "Base-Panoptic-PPA.yaml"
MODEL:
  SEM_SEG_HEAD:
    NAME: "SemSegHeadSingleHeadPPA"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  # 36 epochs = 540000 iterations with batch size of 8
  # decay by a factor of 10 at 24th epoch and 33th epoch
  STEPS: (420000, 500000)
#  STEPS: (360000, 495000)
  MAX_ITER: 540000
OUTPUT_DIR: "./output_panoptic_single_head_ppa_r50_3x"
