_BASE_: "../../../../configs/Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  MASK_ON: True
  SEM_SEG_HEAD:
    PYCONV_OUT_SIZE_LOCAL_CONTEXT: 128
    PYCONV_OUT_SIZE_GLOBAL_CONTEXT: 128
    PYCONV_MERGE_OUT_SIZE: 128
    PYCONV_LOCAL_REDUCTION: 4
    PYCONV_GLOBAL_BINS: 9
    PYCONV_CLS_DROPOUT: 0.1
    LOSS_WEIGHT: 0.5
    PYCONV_FUSE_MODE: "SUM"
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_separated",)
  TEST: ("coco_2017_val_panoptic_separated",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
