_BASE_: "Base-Panoptic-PyConv.yaml"
MODEL:
  SEM_SEG_HEAD:
    NAME: "SemSegMultiScalePyConvHead"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "./output_panoptic_pyconv_r101_3x"
