_BASE_: "Base-Panoptic-PyConv.yaml"
MODEL:
  SEM_SEG_HEAD:
    NAME: "SemSegPyConvHeadV1"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "./output_panoptic_fpn_pyconv_v1_r50_1x"
