_BASE_: "Base-Panoptic-PyConv.yaml"
MODEL:
  SEM_SEG_HEAD:
    NAME: "SemSegMultiScalePyConvHead"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (180000, 247500)
  MAX_ITER: 270000
OUTPUT_DIR: "./output_panoptic_pyconv_r50_3x"
